version: "3.9"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "5001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    dns:
      - 8.8.8.8 
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
    external: true 
